### ISSUE TITLE
Additional CODENOTIFY file

### ISSUE THREAD

**Issue by jcook-uptycs** [sourcegraph/codenotify#30]
I'm looking for a way to add additional code notify rules during the CI run. 

We have a few rules that we want to apply to all our repos. And not have to add/modify the existing CODENOTIFY file on every repo. 

I have tried appending these rules to the CODENOTIFY file in CI. 

```yaml
      - uses: actions/checkout@v3
      - name: Append to CODENOTIFY
        run: |
          touch CODENOTIFY
          echo **/* @test >> CODENOTIFY
          cat CODENOTIFY
      - uses: sourcegraph/codenotify@v0.6.4
```

While this does add the rule to the file, code notify doesn't use the rules from the current branch, but the base branch, so they are not used. 

Any thoughts on how to add these rules in CI?

Thanks for this great tool.
